### ISSUE TITLE
Multi-line cell support in grid mode

### ISSUE THREAD

**Issue by xavierhardy** [gregbanks/python-tabulate#3]
In RST, one of the advantages of using the grid table format (also called grid in tabulate) is to be able to have multi-line cells/rows (not even talking spanning a row over several rows).

All that needs to be done to support this is to detect the maximum number of lines in the row.

See how this example fails:
```python
>>> table
[['spam', 42], ['eggs', 451], ['bacon', 0]]
>>> table[0][0] = "spam\nspam"
>>> print(tabulate(table, headers, tablefmt="grid"))
+-----------+-------+
| item      |   qty |
+===========+=======+
| spam
spam |    42 |
+-----------+-------+
| eggs      |   451 |
+-----------+-------+
| bacon     |     0 |
+-----------+-------+
```

Here is the expected output:
```rst
+-----------+-------+
| item      |   qty |
+===========+=======+
| spam      |    42 |
| spam      |       |
+-----------+-------+
| eggs      |   451 |
+-----------+-------+
| bacon     |     0 |
+-----------+-------+
```

See http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#grid-tables

**Comment by oylbin** [comment]
+1

**Comment by andb0t** [comment]
This is solved, don't know when though. My recent python3 tabulate installation (v. 0.8.1) does it correctly. Is this tabulate repo actually the one behind `pip install tabulate`?

**Comment by calve** [comment]
Looks like the right package is on bitbucket, this commit implements multi line
https://bitbucket.org/astanin/python-tabulate/commits/ea0307d5453470d13ed02f9dd5127dc4c62e14b2

**Comment by xavierhardy** [comment]
Indeed, it works now, thanks a lot.
```sh
$ pip install tabulate
...
Successfully installed tabulate-0.8.2
```

```py
>>> from tabulate import tabulate
>>> table = (("spam\nspam", 42), ("eggs", 451), ("bacon", 0))
>>> headers = ("items", "qty")
>>> print(tabulate(table, headers, tablefmt="grid"))
```
```
+---------+-------+
| items   |   qty |
+=========+=======+
| spam    |    42 |
| spam    |       |
+---------+-------+
| eggs    |   451 |
+---------+-------+
| bacon   |     0 |
+---------+-------+
```
